######################################################################
# Automatically generated by qmake (2.01a) Wed Mar 18 14:01:16 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += widget.h
SOURCES += main.cpp widget.cpp

RESOURCES += \
    background.qrc

OTHER_FILES += \
    widget.qss
